--(1)-Query the top 10 products by total sales value. Include product name, total quantity sold, and total sales value
SELECT TOP 10
	Item Product_Name, 
	FORMAT(SUM(Sales_Quantity), 'N0') Quantity,
	FORMAT(SUM((Sales_Quantity * Sales_Price)),'C0') Revenue
FROM Amazon
GROUP BY Item
ORDER BY SUM((Sales_Quantity * Sales_Price)) DESC

-- (2)-Calculate total revenue generated by each product category. Include the percentage contribution of each 
-- categoryto total revenue
SELECT 
	Category, 
	FORMAT(Revenue, 'C0') Revenue, 
	FORMAT(Revenue/(SELECT SUM(Sales_Quantity * Sales_Price) Total_Revenue FROM Amazon), 'P3') 'Contribution(%)'
FROM 
(SELECT 
	Line_Number Category, --Item Product_name, 
	SUM(Sales_Quantity * Sales_Price) Revenue
FROM Amazon
GROUP BY Line_Number) AS Table2
ORDER BY (Revenue/(SELECT SUM(Sales_Quantity * Sales_Price) Total_Revenue FROM Amazon)) DESC

--- (3)-Query monthly total sales over the past year. Display the sales trend, grouping by month, 
-- return_month sale, last month sale
SELECT
	Year, Month, FORMAT(Revenue, 'C0') Current_Revenue, FORMAT(Previous_Month,'C0') Previous_Month,
	FORMAT(ISNULL((Revenue - Previous_Month)/Previous_Month,0), 'P') Sales_Trend
FROM 
(SELECT
	Year, Month, Revenue,
	LAG(Revenue) OVER ( PARTITION BY Year ORDER BY Year ASC, Month ASC) Previous_Month
FROM 
(SELECT 
	YEAR(DateKey) Year, MONTH(DateKey) Month,
	SUM(Sales_Price * Sales_Quantity) Revenue
FROM Amazon
GROUP BY YEAR(DateKey), MONTH(DateKey)) AS Table1) AS Table2

--- (4)-Identify the best-selling product for each category. Include the total sales for that category
WITH Table3 AS
(SELECT 
	Line_Number, FORMAT(SUM(Revenue),'C0') Total_Revenue
FROM
(SELECT Line_Number ,Item Product_name, SUM(Sales_Price * Sales_Quantity) Revenue  
FROM Amazon
GROUP BY Line_Number, Item) AS Table2
GROUP BY Line_Number),
Table4 AS
(SELECT
	Line_Number, Product_name, FORMAT(Revenue, 'C0') Revenue
FROM 
(SELECT 
	 Line_Number, Item Product_name, 
	 SUM(Sales_Price * Sales_Quantity) Revenue,
	 RANK() OVER (PARTITION BY Line_Number ORDER BY SUM(Sales_Price * Sales_Quantity) DESC) Rank
FROM Amazon 
GROUP BY Item, Line_Number, Sales_Price, Sales_Quantity) AS Table1
WHERE Rank = 1)
-------
SELECT
	T4.Line_Number, Product_name, Revenue, Total_Revenue
FROM Table3 as T3 
JOIN Table4 as T4 ON T3.Line_Number = T4.Line_Number

-- (5)- Compute the average order value for each customer. Include only customers with more than 10 orders.
-- And find the median value of the order

WITH Table1 as
(SELECT 
	Custkey Customer
FROM Amazon
GROUP BY Custkey
HAVING COUNT(Invoice_Number) > 50),
Table2 as  
(		-- Create subtale to made index number column
	SELECT 
		ROW_NUMBER() OVER (ORDER BY Avg_Order_value DESC) Row_num,
		Customer, Avg_Order_value
	FROM 
		(SELECT 
			Custkey Customer, 
			CAST(AVG(Sales_Price * Sales_Quantity) AS Decimal(10,2)) Avg_Order_value
		FROM Amazon
		WHERE Custkey in (SELECT * FROM table1)
		GROUP BY Custkey) as Table3
),
Median_table as
	(SELECT 
		COUNT(*) Number_order,
		CASE
			WHEN COUNT(*) % 2 = 0 THEN COUNT(*)/2
			ELSE (COUNT(*)+1) / 2
		END Median_value1,
		CASE
			WHEN COUNT(*) % 2 = 0 THEN (COUNT(*)+2)/2
			ELSE (COUNT(*)+1) / 2
		END Median_value2
	FROM Table2)
-- Find the median value
SELECT
	FORMAT(AVG(Avg_order_value), 'C2') Median_value_of_Order
FROM 
(SELECT 
	Row_num,
	Customer,
	Avg_order_value
FROM Table2 as t2 
JOIN Median_table as mt ON mt.Median_value1 = t2.Row_num OR mt.Median_value2 = t2.Row_num) as Result

--- (6)- Find the top 10 sellers based on total sales value. And display their percentage orders for 
-- total sales of Sales_Rep
WITH Sale_Total AS
(SELECT 
	SUM(Sales_Price * Sales_Quantity) Total_Revenue
FROM Amazon),
Sales as
(SELECT
	 Sales_Rep Seller, 
	 FORMAT(SUM(Sales_Price * Sales_Quantity),'C0') Revenue,
	 SUM(Sales_Price * Sales_Quantity) Sales_Value
FROM Amazon
GROUP BY Sales_Rep)
-----
SELECT TOP 10
	Seller, Revenue, 
	FORMAT((Sales_Value/(SELECT*FROM Sale_Total)),'P2') '%Contribution'
FROM Sales
ORDER BY Sales_Value DESC

--- (7)- Top 10 product with highest Deceasing revenue ratio compare to last_year(2018) and current_year(2019)
-- Return product_id, product_name, categroy_name, 2018 revenue and 2019 revenue decrease ratio at end round 
-- Note: Decrease ratio = cr-ls/ls* 100
WITH Table1 AS
(SELECT  
	YEAR(Invoice_date) Year, MONTH(Invoice_date) Month,
	Order_Number, Item Product,
	SUM(Sales_Price * Sales_Quantity) Revenue
FROM Amazon 
GROUP BY Order_Number, Item, YEAR(Invoice_date), MONTH(Invoice_date)
HAVING YEAR(Invoice_date) BETWEEN 2018 AND 2019),
Table2 AS
(
	SELECT 
		Year, Month, SUM(Revenue) Total_Revenue
	FROM Table1
	GROUP BY Year, Month
)
------
SELECT 
	Cur.Year Current_Year, Cur.Month Month,
	FORMAT(Cur.Total_Revenue,'C0') Current_Revenue, 
	ISNULL(Pre.Year,'') Previous_Year, ISNULL(Pre.Month,'') Previous_Month,
	ISNULL(FORMAT(Pre.Total_Revenue,'C2'),'') Previous_Revenue,
	ISNULL(FORMAT(((Cur.Total_Revenue - Pre.Total_Revenue)/CAST (Pre.Total_Revenue AS decimal(10,2))), 'P2'),'') Decrease_Ratio
FROM Table2 as Cur 
LEFT JOIN Table2 as Pre ON Cur.Year = Pre.Year + 1 AND Cur.Month = Pre.Month 
WHERE Cur.Year != 2018
